### PR TITLE
interfaces: update template with new syscalls

### PR DESCRIPTION
**Pull request by maykathm**

### CODE REVIEW

**Comment by maykathm** [comment]
Looking through the history of adding syscalls to templates in snapd, I see that most of the time the addition didn't come with an additional test. Given the nature of the calls seem to be of a similar vein, I didn't think tests for these syscalls would be necessary. If I'm off on that, then I am happy to add new spread tests.

**Review by zyga — APPROVED** [review]
LGTM based on prior discussions

**Review by alexmurray — APPROVED** [review]
LGTM

**Comment by maykathm** [comment]
All spread failures are found elsewhere and not caused by this PR

**Review by bboozzoo — APPROVED** [review]
Thanks

**Pull request merged**
