### PR TITLE
build-aux/snap: update vendored apparmor to latest 4.0.2 release

### PR DESCRIPTION
**Pull request by alexmurray**
Signed-off-by: Alex Murray <alex.murray@canonical.com>

-------

Thanks for helping us make a better snapd!
Have you signed the [license agreement](https://www.ubuntu.com/legal/contributors) and read the [contribution guide](https://github.com/snapcore/snapd/blob/master/CONTRIBUTING.md)?

### CODE REVIEW

**Review by zyga — APPROVED** [review]
Thank you for adding the checksum.

**Review by valentindavid — APPROVED** [review]

**Comment by olivercalder** [comment]
Is there any way to vendor the version of AppArmor 4.0.2 from ubuntu instead of upstream, so we can have support for AppArmor Prompting?

**Comment by alexmurray** [comment]
> Is there any way to vendor the version of AppArmor 4.0.2 from ubuntu instead of upstream, so we can have support for AppArmor Prompting?

Yep - I just added it now in https://github.com/canonical/snapd/pull/14250/commits/2e7081713e54382c27bd582be2995cc48697ea13 - with this in place we get the following (note the presence of `parser:prompt`)

```
$ snap debug sandbox-features | grep apparmor:
kernel:caps kernel:dbus kernel:domain kernel:domain:attach_conditions kernel:file kernel:io_uring kernel:ipc kernel:mount kernel:namespaces kernel:network kernel:network_v8 kernel:policy kernel:policy:permstable32:allow kernel:policy:permstable32:audit kernel:policy:permstable32:complain kernel:policy:permstable32:cond kernel:policy:permstable32:deny kernel:policy:permstable32:hide kernel:policy:permstable32:kill kernel:policy:permstable32:label kernel:policy:permstable32:prompt kernel:policy:permstable32:quiet kernel:policy:permstable32:subtree kernel:policy:permstable32:tag kernel:policy:permstable32:xindex kernel:policy:unconfined_restrictions kernel:policy:versions kernel:ptrace kernel:query kernel:query:label kernel:rlimit kernel:signal parser:allow-all parser:cap-audit-read parser:cap-bpf parser:include-if-exists parser:io-uring parser:mqueue parser:prompt parser:qipcrtr-socket parser:snapd-internal parser:unconfined parser:unsafe parser:userns parser:xdp policy:default support-level:full
```

**Review by olivercalder — APPROVED** [review]
Thank you for including the prompting patch!

**Comment by ernestl** [comment]
Hi @alexmurray @olivercalder, 

I see test failures like: apparmor_parser output:
2024-08-02T02:29:33.0508463Z /snap/snapd/x1/usr/lib/snapd/apparmor_parser: Unable to replace "snap.test-snapd-rsync-core22.rsync".  Profile doesn't conform to protocol

**Comment by bboozzoo** [comment]
More debugging. Fortunately I can easily reproduce this by trying to install `hello-world --devmode` on 16.04, and we're lucky there's an apparent error in cleanup so that the profiles stay behimd. I have confimed that we're using the internal apparmor parser as first, `snap debug sandbox-features` reports `parser:snap-internal`. Moreover, the profile uses `#include if exists` which the host apparmor_parser chokes on.

So all in all the actual command we run is:

```
google:ubuntu-16.04-64 .../tests/main/snap-run-devmode-classic# /snap/snapd/current/usr/lib/snapd/apparmor_parser \
    --config-file /snap/snapd/current/usr/lib/snapd/apparmor/parser.conf \
    --base /snap/snapd/current/usr/lib/snapd/apparmor.d \
    --policy-features /snap/snapd/current/usr/lib/snapd/apparmor.d/abi/4.0 \
    -r /var/lib/snapd/apparmor/profiles/snap.hello-world.evil 
/snap/snapd/current/usr/lib/snapd/apparmor_parser: Unable to replace "snap.hello-world.evil".  Profile doesn't conform to protocol
```

and the kernel logs:

```
[ 3827.073606] audit: type=1400 audit(1723041897.450:243): apparmor="STATUS" info="failed to unpack policydb" error=-71 profile="unconfined" name="snap.hello-world.evil" pid=18434 comm="apparmor_parser" name="snap.hello-world.evil" offset=7984
```

**Comment by jrjohansen** [comment]
My first guess was we were generating an xtable when we shouldn't but the complain flag shouldn't affect this. I will try and reproduce, but in the meantime @bboozzoo can you attach or send me the compiled profile that is failing? 

you can get that by replacing the -r in the command with -S and then redirecting stdout, or with -o filename to write the binary to a file.

**Comment by bboozzoo** [comment]
[failing-profile.tar.gz](https://github.com/user-attachments/files/16533911/failing-profile.tar.gz)
I've uploaded the failing profile and binary output, there should be 2 files inside:
```
$ tar tvf failing-profile.tar.gz 
-rw-r--r-- root/root     86278 2024-08-07 22:26 profile.bin
-rw-r--r-- root/root     24057 2024-08-07 22:27 snap.hello-world.evil
```
Let me know if you need anything else.

**Comment by jrjohansen** [comment]
The following patch fixes the issue, it is available in https://launchpad.net/~apparmor-dev/+archive/ubuntu/apparmor-devel as well.

```
From 111eec7de230b51e71020a565a099d3e5491692e Mon Sep 17 00:00:00 2001
From: John Johansen <john.johansen@canonical.com>
Date: Thu, 8 Aug 2024 01:44:05 -0700
Subject: [PATCH] parser: fix protocol error on older kernels caused by
 additional xtable

Older kernels do not support an xtable grouped with the policy dfa.
The presence of a policy.dfa does not indicate whether we should create
an xtable with the policy dfa.

Instead the check should be if the kernel supports the extended
permstable32 format.

Signed-off-by: John Johansen <john.johansen@canonical.com>
---
 parser/parser_interface.c | 14 +++++++-------
 1 file changed, 7 insertions(+), 7 deletions(-)

diff --git a/parser/parser_interface.c b/parser/parser_interface.c
index 8a0ed69fc..9e46bdca7 100644
--- a/parser/parser_interface.c
+++ b/parser/parser_interface.c
@@ -539,13 +539,13 @@ void sd_serialize_profile(std::ostringstream &buf, Profile *profile,
 		sd_write_struct(buf, "policydb");
 		sd_serialize_dfa(buf, profile->policy.dfa, profile->policy.size,
 				 profile->policy.perms_table);
-	if (profile->policy.dfa) {
-		// fprintf(stderr, "profile %s: policy xtable\n", profile->name);
-		// TODO: this is dummy exec make dependent on V1
-		sd_serialize_xtable(buf, profile->exec_table,
-				    profile->uses_prompt_rules && prompt_compat_mode == PROMPT_COMPAT_PERMSV1 ?
-				    profile->policy.perms_table.size() : 0);
-	}
+		if (kernel_supports_permstable32) {
+			sd_serialize_xtable(buf, profile->exec_table,
+				profile->uses_prompt_rules &&
+				prompt_compat_mode == PROMPT_COMPAT_PERMSV1 ?
+					profile->policy.perms_table.size() : 0);
+
+		}
 		sd_write_structend(buf);
 	}
 
-- 
2.43.0

```

**Comment by bboozzoo** [comment]
@jrjohansen thank you for the patch. I've cherry picked it from the deb and pushed here. Let's see if the tests are happier now.

**Comment by alexmurray** [comment]
Thanks for the patch @jrjohansen - this is looking great.

@ernestl et al - spread is looking much happier now - can this be merged?

**Pull request merged**
