### PR TITLE
o/snapstate: make sure to put aux info from store on SnapSetup

### PR DESCRIPTION
**Pull request by andrewphelpsj**
This was dropped (by me) accidentally a while back when introducing components. This adds it back and adds some tests for it.

### CODE REVIEW

**Review by pedronis — APPROVED** [review]
thank you

**Review by olivercalder — APPROVED** [review]
Looks good to me, thank you!

**Comment by olivercalder** [comment]
> Could the `snapd` snap be used instead of `core24`?

Or perhaps `snap-store` if we want a guaranteed snap with media.

**Comment by andrewphelpsj** [comment]
Only required failing test here is `google:ubuntu-20.04-64:tests/main/nvidia-files:535_server`.

**Pull request merged**
