### PR TITLE
interfaces: grant access to gcin socket location in desktop-legacy

### PR DESCRIPTION
**Pull request by ifurther**
gcin should use socket for this

### CODE REVIEW

**Review by alexmurray — APPROVED** [review]
LGTM - as per https://sources.debian.org/src/gcin/2.9.0+dfsg1-2/im-srv.cpp/?hl=185#L181 and https://sources.debian.org/src/gcin/2.9.0+dfsg1-2/im-addr.cpp/?hl=9#L9 gcin creates a UNIX stream socket with address `/tmp/gcin-$USER/socket-:0.0-gcin` (or similar) where `$USER` is the username and the `-:0.0-gcin` suffix is not fixed but based on the `$DISPLAY` and any `XMODIFIERS`.

As such this peer addr looks quite sufficient.

**Comment by ifurther** [comment]
Hi @alexmurray  @Meulengracht  How will do next setup ?

**Comment by alexmurray** [comment]
@ifurther this requires more reviews from members of the snapd team.

**Comment by zyga** [comment]
I think this will need a rebase. Let me try one.

**Review by ernestl — APPROVED** [review]
Looks good, thanks

**Comment by ernestl** [comment]
Needs rebase

**Pull request merged**
