### PR TITLE
cmd/snap: rename cmd_paths to cmd_debug_paths

### PR DESCRIPTION
**Pull request by bboozzoo**
Debug command implementation files are typically named cmd_debug_*.go

Thanks for helping us make a better snapd!
Have you signed the [license agreement](https://www.ubuntu.com/legal/contributors) and read the [contribution guide](https://github.com/snapcore/snapd/blob/master/CONTRIBUTING.md)?

### CODE REVIEW

**Review by zyga — APPROVED** [review]

**Review by ZeyadYasser — APPROVED** [review]
Thanks!

**Comment by ernestl** [comment]
Hi @bboozzoo, what about these?

**Incorrectly named and not mentioned in help**
cmd_get_base_declaration.go    | addDebugCommand("get-base-declaration"
cmd_get_base_declaration.go    | addDebugCommand("base-declaration"
cmd_ensure_state_soon.go        | addDebugCommand("ensure-state-soon"
cmd_can_manage_refreshes.go | addDebugCommand("can-manage-refreshes"

**Incorrectly named**
cmd_confinement.go           | addDebugCommand("confinement"
cmd_paths.go                      | addDebugCommand("paths"
cmd_sandbox_features       | addDebugCommand("sandbox-features"
cmd_connectivity_check.go | addDebugCommand("connectivity"

**Review by ernestl — COMMENTED** [review]
Question obout other cases

**Review by MiguelPires — APPROVED** [review]
thanks

**Review by ernestl — APPROVED** [review]
Thanks

**Pull request merged**
