### PR TITLE
tests: correct snapd revision number in snapd-refresh-undo for ARM

### PR DESCRIPTION
**Pull request by maykathm**

### CODE REVIEW

**Review by andrewphelpsj — APPROVED** [review]
Thanks!

**Review by miguelpires — APPROVED** [review]
thanks

**Review by olivercalder — COMMENTED** [review]
Would it be possible to find an arm64 snap revision close to 18357 and manually refresh to that instead if the runner arch is arm64?

**Comment by olivercalder** [comment]
I believe the corresponding arm64 revision for the amd64 revision 18357 is 18363. Both are snapd version 2.58.2. The previous arm64 revision from 18357 is 18353, which is snapd version 2.58.1+git1.g7f1d30a.

I would propose we switch on `$(uname -m)` and if it's `arm64`, we refresh to revision 18363 instead, and carry on with the test.

**Review by olivercalder — APPROVED** [review]
Thanks, looks great! PR title could now use an update.

**Pull request merged**
