### PR TITLE
interface/screen_inhibit_control: Improve screen inhibit control for use on core

### PR DESCRIPTION
**Pull request by er-vin**
* Make it available on Ubuntu Core
* Receive notifications for inhibit changes, plugged application could change the inhibit status but had no way to be notified when it actually changes.

### CODE REVIEW

**Review by alexmurray — APPROVED** [review]
LGTM!

**Review by jhenstridge — CHANGES_REQUESTED** [review]
The addition of access to the `HasInhibitChanged` signal looks fine (it is included in [this copy of the spec](https://web.archive.org/web/20090417010057/http://people.freedesktop.org/~hughsient/temp/power-management-spec-0.2.html)). Making the interface implicit on core seems suspect.

Checking my KDE Core Desktop VM, `org.freedesktop.PowerManagement` on the session bus is owned by `org_kde_powerdevil` running with the AppArmor label `snap.plasma-desktop-session.plasma-powerdevil`. Similarly `org.freedesktop.ScreenSaver` is owned by a process with the label `snap.plasma-desktop-session.plasma-kwin-wayland`. So allowing communication with `label=unconfined` does not sound like it would actually enable any communication here.

For proper operation on Core, the interface would need to be modified to allow a snap to provide the slot.

**Comment by ernestl** [comment]
Changed milestone to 2.67, needs more time.

**Comment by er-vin** [comment]
> For proper operation on Core, the interface would need to be modified to allow a snap to provide the slot.

It has been reworked in this direction.

**Review by jhenstridge — APPROVED** [review]
Looks good!

**Comment by er-vin** [comment]
Just did a rebase on latest master to ease the re-review.

**Review by alexmurray — APPROVED** [review]
Still LGTM!

**Comment by er-vin** [comment]
@Meulengracht static checks are fixed now, should be good to merge now.

**Pull request merged**
