### PR TITLE
o/snapstate: do not keep the state lock while removing snap files

### PR DESCRIPTION
**Pull request by bboozzoo**
Do not take the state lock when removing snap files, since it is not known how long the removal will take. We have observed a system in the field, where there were issues with I/O on the storage device and unlink() took significant time, this preventing snapd from functioning normally as the state lock was held.

Related: SNAPDENG-26617

Thanks for helping us make a better snapd!
Have you signed the [license agreement](https://www.ubuntu.com/legal/contributors) and read the [contribution guide](https://github.com/snapcore/snapd/blob/master/CONTRIBUTING.md)?

### CODE REVIEW

**Review by zyga — APPROVED** [review]
I cannot see anthing wrong with this approach. LGTM

**Review by pedronis — COMMENTED** [review]
if I remember correctly here are some directories that need to exists across all instances with parallel installs, does this function touch those?

a simple install of the same snap while removing will create a conflict I think? can you double check, but as I said not sure whether there are issues for parallel installs

**Comment by bboozzoo** [comment]
> if I remember correctly here are some directories that need to exists across all instances with parallel installs, does this function touch those?
> 
> a simple install of the same snap while removing will create a conflict I think? can you double check, but as I said not sure whether there are issues for parallel installs

Yes, the non-instance directories, but this code is handled bit later and with the state lock held, see https://github.com/canonical/snapd/blob/2a12d00aebc147b5a5e89438b3bef92b8235526a/overlord/snapstate/handlers.go#L3596-L3603

**Comment by pedronis** [comment]
> Yes, the non-instance directories, but this code is handled bit later and with the state lock held

thanks for chasing this, could you add a comment around there that we need to old the lock because the directories presence/absence is across snaps so conflicts don't protect us? do we hold the lock when we create the dirs?

**Review by MiguelPires — APPROVED** [review]
lgtm

**Comment by bboozzoo** [comment]
> thanks, did you find the corresponding creation code and whether we hold the lock there?

per discussion on MM, I think there may be a separate bug, unrelated to this PR. Filed https://warthogs.atlassian.net/browse/SNAPDENG-31335 to investigate further

**Pull request merged**
