### PR TITLE
overlord/fdestate, overlord/snapstate: tweak unit tests, capture logs, formatting

### PR DESCRIPTION
**Pull request by bboozzoo**
Assorted minor tweaks cherry picked from https://github.com/canonical/snapd/pull/14615

Related: [SNAPDENG-32509](https://warthogs.atlassian.net/browse/SNAPDENG-32509)

[SNAPDENG-32509]: https://warthogs.atlassian.net/browse/SNAPDENG-32509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by ZeyadYasser — APPROVED** [review]
LGTM!

**Review by pedronis — COMMENTED** [review]
@bboozzoo this has conflicts now has we have changed KeyslotRolesParameters.Models to be pointers

**Comment by bboozzoo** [comment]
> @bboozzoo this has conflicts now has we have changed KeyslotRolesParameters.Models to be pointers

I dropped the last patch which caused conflicts.

**Review by pedronis — APPROVED** [review]
+1

**Pull request merged**
