### PR TITLE
interfaces/lxd-support: add support for allow all in AppArmor

### PR DESCRIPTION
**Pull request by alexmurray**
Similarly to the recent changes to the steam-support interface in #14229, the
lxd-support interface also needs to support an essentially unconfined LXD by
giving it all the possible permissions. This was previously done through the use
of the unconfined AppArmor profile mode, along with the userns,
permission. However, due to issues with apparmor_parser not correctly generating
all the required permissions when using the unconfined profile mode, it is
better to instead follow the same pattern as is now done in steam-support and
make use of the allow all, AppArmor parser feature/syntax when available, or to
fallback to generating a profile which includes all the possible permissions
when this is not available (as well as retaining the unconfined profile mode).

Signed-off-by: Alex Murray <alex.murray@canonical.com>

-------

Thanks for helping us make a better snapd!
Have you signed the [license agreement](https://www.ubuntu.com/legal/contributors) and read the [contribution guide](https://github.com/snapcore/snapd/blob/master/CONTRIBUTING.md)?

### CODE REVIEW

**Review by zyga — APPROVED** [review]
One interesting side effect of this implementation is that the effective apparmor profile will still contain the base template, as well as snippets from all the connected interfaces.

One other interesting observation is that we have the classic confinement switch for installing snaps and perhaps we should also have an unconfined switch for snaps such as legacy and steam.

If we were to do this with a confinement option the backend could generate a very small profile without all the extra snippets.

**Review by bboozzoo — APPROVED** [review]
LGTM

**Comment by pedronis** [comment]
@alexmurray this breaks older lxd on jammy for example

**Comment by pedronis** [comment]
I get this on jammy:

```
$ snap install lxd
2024/08/16 19:37:22.489524 logger.go:93: DEBUG: restarting into "/snap/snapd/current/usr/bin/snap"
error: cannot perform the following tasks:
- Start snap "lxd" (29568) services (systemctl command [start snap.lxd.activate.service] failed with exit status 1: stderr:
Job for snap.lxd.activate.service failed because the control process exited with error code.
See "systemctl status snap.lxd.activate.service" and "journalctl -xeu snap.lxd.activate.service" for details.)
$ journalctl -xeu snap.lxd.activate.service
Aug 16 19:37:33 thirtyfive lxd.activate[7253]: DEBUG: working directory restored to /var/snap/lxd/29568
Aug 16 19:37:33 thirtyfive lxd.activate[7253]: DEBUG: -- snap startup {"stage":"snap-confine to snap-exec", "time":"1723829853.1780>
Aug 16 19:37:33 thirtyfive lxd.activate[7253]: logger.go:99: DEBUG: -- snap startup {"stage":"snap-exec to app", "time":"1723829853>
Aug 16 19:37:33 thirtyfive lxd.activate[7253]: [7253] aa-exec: ERROR: insufficient permissions to change to the profile 'unconfined'
Aug 16 19:37:33 thirtyfive systemd[1]: snap.lxd.activate.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by alexmurray** [comment]
Oh, that's a shame. Yep let's revert it and I can take a look on Monday.

**Comment by alexmurray** [comment]
I'm surprised the existing spread tests didn't catch that. Perhaps we need a lxd smoke test like the microk8s one?

**Comment by tomponline** [comment]
@alexmurray if you could use latest/candidate lxd snap channel that would help catch regressions earlier too

**Pull request merged**
