### PR TITLE
tests: install missing dependency to fix oracular building

### PR DESCRIPTION
**Pull request by sergiocazzolato**
In oracular the packages systemd-cryptsetup and systemd-dev are not included anymore in the base image which is used in google and openstack.

This change adds this package as a tests dependency to avoid the following error when building snapd deb package.

To reproduce the error, run:
SPREAD_SNAPD_DEB_FROM_REPO=false spread -debug -no-debug-output google:ubuntu-24.10-64:tests/main/abort

Error:

configure: error: Package requirements (udev) were not met:

Package 'udev', required by 'virtual:world', not found

### CODE REVIEW

**Review by ernestl — APPROVED** [review]
Thanks looks correct.

`pkg-config --path udev` -> `/usr/share/pkgconfig/udev.pc`
`dpkg -L systemd-dev | grep udev` -> `/usr/share/pkgconfig/udev.pc`

**Review by alfonsosanchezbeato — APPROVED** [review]
LGTM, thanks

**Review by zyga — APPROVED** [review]
I will look separately if we are missing anything in our build dependencies when built cleanly (sbuild).

**Review by bboozzoo — APPROVED** [review]
LGTM

Do we need to update packaging deps on Ubuntu as well?

**Comment by ernestl** [comment]
Failures are known.

**Pull request merged**
