### PR TITLE
tests: Let go ignore the tests directory

### PR DESCRIPTION
**Pull request by upils**
Add an empty go.mod in tests/ so go will not zip the content when building the modules.

This is now needed because some tests cases now rely in files named containing invalid char according to
https://go.dev/ref/mod#zip-path-size-constraints

### CODE REVIEW

**Comment by upils** [comment]
I tested by renaming the module in my fork and getting the module in a newly created project.

See https://sum.golang.org/lookup/github.com/upils/snapd@v0.0.0-20241008132100-263a040392de (the commit is now gone since I dropepd it to submit the PR)

**Review by zyga — APPROVED** [review]
I understand the problem and I think this is an elegant solution.

+1 assuming my understanding is correct and tests don't regress unexpectedly.

**Comment by upils** [comment]
I just moved the file down the tree since some tests called `go install ./tests/lib/...`. Let's see if this is enough.

**Comment by upils** [comment]
Should be closed if https://github.com/canonical/snapd/pull/14590 is successfully merged.

**Comment by ZeyadYasser** [comment]
Closing in favor of https://github.com/canonical/snapd/pull/14590

**Pull request closed without merging**
