### PR TITLE
interfaces: allow kernels to have content slots

### PR DESCRIPTION
**Pull request by pedronis**

### CODE REVIEW

**Review by alfonsosanchezbeato — APPROVED** [review]
LGTM, thanks

**Review by ZeyadYasser — APPROVED** [review]
LGTM, Thank you!

Double checking my understnding, This is needed to share libraries, right?

**Comment by pedronis** [comment]
@ZeyadYasser 

> Double checking my understnding, This is needed to share libraries, right?

yes, that's the main use case in general and also the use case that we are trying to enable here

**Comment by pedronis** [comment]
All failures look unrelated to the change

**Comment by alexmurray** [comment]
@jslarraz FYI we likely have to update review-tools to handle this change

**Comment by alexmurray** [comment]
> @jslarraz FYI we likely have to update review-tools to handle this change

I just filed https://bugs.launchpad.net/review-tools/+bug/2084406 to track this on the review-tools side

**Pull request merged**
