### PR TITLE
tests/main/apparmor-prompting-snapd-startup: compatibility with older jq

### PR DESCRIPTION
**Pull request by bboozzoo**
jq < 1.7 chokes on indexing with with a dot separator

cherry pick from #14294 

Thanks for helping us make a better snapd!
Have you signed the [license agreement](https://www.ubuntu.com/legal/contributors) and read the [contribution guide](https://github.com/snapcore/snapd/blob/master/CONTRIBUTING.md)?

### CODE REVIEW

**Review by ZeyadYasser — APPROVED** [review]

**Review by zyga — APPROVED** [review]

**Comment by olivercalder** [comment]
Is this fix necessary to be included in 2.65? Or why would jq be old enough for this to matter on the systems where this test runs?

**Comment by olivercalder** [comment]
This will need to be rebased to include additional `.result.[0]` from #14421 once it lands. I'd rather get it landed and included in 2.65 rather than push a fix to that branch now.

**Comment by olivercalder** [comment]
I've implemented these changes as part of #14421, since we're pushing back the release of that fix until tomorrow morning anyway.

**Comment by ernestl** [comment]
Thanks, this was incorporated into https://github.com/canonical/snapd/pull/14421.
Not required anymore.

**Comment by ernestl** [comment]
Closing

**Pull request closed without merging**
