### PR TITLE
interfaces/system_packages_doc: Add jquery-ui.

### PR DESCRIPTION
**Pull request by nteodosio**
This is a follow up to #13130, in which access was allowed to /usr/share/javascript/{sphinxdoc,jquery} and /usr/share/sphinx_rtd_theme, but jquery-ui was left out, causing https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/2032992/comments/31.

It would be easier to allow access to the whole of /usr/share/javascript so let me know if this would be allowed (I'm assuming it would not) so I can close this and submit one for that.

### CODE REVIEW

**Comment by vpa1977** [comment]
Note: we can use Lintian checks[1] as the basis for the whitelist, but this should be tracked quite closely.

[1] https://git.launchpad.net/ubuntu/+source/lintian/tree/lib/Lintian/Check/Languages/Javascript/Embedded.pm

**Review by zyga — APPROVED** [review]
Thanks!

**Review by alexmurray — APPROVED** [review]
Hmm I also tend to think the current whack-a-mole approach is bound to cause similar issues BUT `/usr/share/javascript` is used for more than just JS UI packages (it is also used for various nodejs packages etc) - BUT given this is just providing read access to things already installed, the risk is quite small (other than an info-leak about which packages are installed on the host, which I do not think is really a security issue).

As such, +1 from me for this request but I would also be fine with read-access to all of `/usr/share/javascript/` as well.

**Comment by nteodosio** [comment]
Closing in favor of #14303.

**Pull request closed without merging**
