### PR TITLE
tests: move debian-12 and sid to openstack

### PR DESCRIPTION
**Pull request by sergiocazzolato**
This change moves the non-required debian system to openstack

### CODE REVIEW

**Review by zyga — APPROVED** [review]
Thank you

**Review by bboozzoo — APPROVED** [review]
LGTM

**Comment by bboozzoo** [comment]
```
  Fetching test-snapd-sh (13)
error: cannot extract "*" to "/home/test/tmp/kernel": FATAL ERROR: write_file: failed to create file /home/test/tmp/kernel/modules/5.4.0-200-generic/kernel/drivers/platform/x86/dell-wmi-aio.ko, because No space left on device
-----
.
2024-12-04 19:18:20 Debug output for google-distro-2:opensuse-tumbleweed-64:tests/main/prepare-image-validation-sets (dec041906-147488) : saved to file spread-logs/google-distro-2_opensuse-tumbleweed-64_tests_main_prepare-image-validation-sets.debug.log
2024-12-04 19:18:20 Restoring google-distro-2:opensuse-tumbleweed-64:tests/main/prepare-image-validation-sets (dec041906-147488)...
```

**Comment by bboozzoo** [comment]
and microk8s-smoke failed, but I think we had a fix?

**Pull request merged**
