### PR TITLE
many: add coredump options

### PR DESCRIPTION
**Pull request by alfonsosanchezbeato**
Proposing https://github.com/canonical/snapd/pull/14202 again as it had to be reverted (https://github.com/canonical/snapd/pull/14374) due to failures on UC16 tests.

The problem was due to trying to create a folder in old UC where it was not possible, and due to the way system options work this code was being run even for any `snap set system ...` command. https://github.com/canonical/snapd/pull/14379/commits/133841500dd5e9748f8fa16d687357a70a0ebf85 is the code change to avoid this.

### CODE REVIEW

**Comment by alfonsosanchezbeato** [comment]
Draft for the moment as the intention is to check first what is going on with the tests.

**Comment by alfonsosanchezbeato** [comment]
In fact, it is not that the test gets run on UC16, but that due to the way system options work some code of this PR is actually run on UC16.

**Review by Meulengracht — APPROVED** [review]
Thank you! Thanks for reopening this (and I can see the test is now passing on the other UC versions).

**Review by ernestl — APPROVED** [review]
Thanks,

However we need test in better state before we can merge.

**Pull request merged**
