### PR TITLE
tests: added dependabot for updating dependencies

### PR DESCRIPTION
**Pull request by maykathm**
When merged to master, dependabot will check for updates in go dependencies and github actions weekly. When it finds an out-of-date package, it will automatically open a pull request. Here's an example of the pull requests opened on my fork of snapd when I pushed this yaml file to master: https://github.com/maykathm/snapd/pulls

### CODE REVIEW

**Comment by maykathm** [comment]
It looks like the dependabot will only send alerts for security updates. One option to keep the number of pull requests down is to group the changes. 

Here's an example where I had the bot group together: 
- major version bumps: https://github.com/maykathm/snapd/pull/14
- minor+patch version bumps: https://github.com/maykathm/snapd/pull/13

To ignore an update, one would have to either issue a command like `@dependabot ignore <dep-name> major version` or add that ignore command to the dependabot.yaml file. The bot doesn't automatically update the pull request though so ignores would need to be followed by an additional manual commit.

Obviously one can also change the frequency of updates. I currently have it set to weekly.

What do you think @ernestl and @sergiocazzolato?

**Review by ernestl — COMMENTED** [review]
Thanks, looks good. 
- Lets discuss with the team to get consensus on interval and grouping.
- Once fix cadence releases become a thing, we can consider doing this at a date right after such a release to ensure maximum time between updates and release attempts.

**Comment by ernestl** [comment]
Blocked, decided to first discuss with the team during engineering sprint.

**Review by zyga — APPROVED** [review]
Looks good, we should merge it as it will only open PRs and not automatically update anything. I'm not aware of any downsides.

**Review by ernestl — APPROVED** [review]
Thanks

**Pull request merged**
